module.exports.OPEN_SPOTS = "Список доступных матчей";
module.exports.CREATE_SPOT = "Создать матч";
module.exports.USER_ERROR_MSG = "Что-то пошло не так, попробуйте еще раз!";
module.exports.NOTIFIED_ONE_HOUR_BEFORE = "Ваш матч стартует через *час*";
module.exports.NOTIFIED_ONE_DAY_BEFORE = "Ваш матч стартует через *24 часа*";
module.exports.NEW_SPOT_IS_CREATED = "*=> Создан новый матч*";
module.exports.OPEN_SPOTS_LIST = "*=> Список доступных матчей*";
module.exports.INSERT_SPOT_DATE = "Введите дату проведения матча";
module.exports.INSERT_SPOT_LOCATION = "Введите место проведения матча";
module.exports.INSERT_SPOT_COST = "Введите цену за одного человека";
module.exports.INSERT_SPOT_MEMBERS = "Введите количество человек";
module.exports.INSERT_SPOT_PAYMENT_INFO = "Введите доп. информацию по оплате";
