const SPOT_STATUS = {
  "OPEN": "open",
  "CLOSED": "closed",
  "WAIT_GROUP": "wait_group"
};

const NOTIFY_STATUS = {
  "NOTIFIED_ONE_DAY_BEFORE": "NOTIFIED_ONE_DAY_BEFORE",
  "NOTIFIED_ONE_HOUR_BEFORE": "NOTIFIED_ONE_HOUR_BEFORE",
  "NOT_YET_NOTIFIED": "NOT_YET_NOTIFIED"
};

module.exports.NOTIFY_STATUS = NOTIFY_STATUS;
module.exports.SPOT_STATUS = SPOT_STATUS;
